version: "2.0"

services:
  forum:
    build: ./forum
    links:
      - redis

  redis:
    image: redis:3.0.7
    ports:
      - 6379:6379

  web:
    build: ./web
    ports:
      - 8080:8080
    links:
      - forum
    environment:
      - PORT=8080
