nodebb:
  build: ./nodebb
  ports:
    - 4567:4567
  links:
    - redis

redis:
  image: redis:3.0.7
  ports:
    - 6379:6379

web:
  build: ./web
  ports:
    - 8080:8080
  command: npm run dev
  links:
    - nodebb
  environment:
    NODE_ENV: development
  volumes:
    - ./web:/home/app/web
    - ./web/node_modules:/home/app/web/node_modules
