version: "2.0"

services:
  forum:
    environment:
      - NODE_ENV=development

  web:
    environment:
      - DEBUG=jetboardlimited:*
      - NODE_ENV=development
      - DISQUS_URL=https://jetboardlimited.disqus.com/embed.js
      - SERVER_HOST_URL=http://localhost:8080
    volumes:
      - ./web:/node
    command: npm run dev
