version: "2.0"

services:
  forum:
    container_name: jbl-forum
    build: ./forum
    ports:
      - 127.0.0.1:4567:4567
    links:
      - redis

  redis:
    container_name: jbl-redis
    image: redis:3.0.7
    ports:
      - 127.0.0.1:6379:6379

  web:
    container_name: jbl-web
    build: ./web
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - PORT=8080

