version: "2.0"

services:
  forum:
    environment:
      - NODE_ENV=development
      - FORUM_URL=http://localhost:4567

  web:
    environment:
      - DEBUG=jetboardlimited:*
      - NODE_ENV=development
      - FORUM_URL=http://localhost:4567
      - DISQUS_URL=https://jetboardlimited.disqus.com/embed.js
      - SERVER_HOST_URL=http://localhost:8080
    volumes:
      - ./web/bin:/node/bin
      - ./web/tests:/node/tests
      - ./web/views:/node/views
      - ./web/public:/node/public
      - ./web/routes:/node/routes
      - ./web/app.js:/node/app.js
    command: npm run dev
