version: "2.0"

services:
  forum:
    build: ./forum
    ports:
      - 127.0.0.1:4567:4567
    links:
      - redis

  redis:
    image: redis:3.0.7
    ports:
      - 127.0.0.1:6379:6379

  web:
    build: ./web
    ports:
      - 127.0.0.1:8080:8080
    links:
      - forum
    environment:
      - PORT=8080
