forum:
  build: ./forum
  ports:
    - 4567:4567
  links:
    - redis

redis:
  image: redis:3.0.7
  ports:
    - 6379:6379

web:
  build: ./web
  ports:
    - 8080:8080
  links:
    - forum
  environment:
    - DEBUG=jetboardlimited:*
    - NODE_ENV=development
    - PORT=8080
  volumes:
    - ./web:/home/app/web
    - ./web/node_modules:/home/app/web/node_modules
  command: npm run dev
